---
apiVersion: v1
kind: Service
metadata:
  name: dummy-api
spec:
  selector:
    app: dummy-api
  ports:
  - port: 80
    targetPort: 3000
    name: http
  - port: 443
    targetPort: 3000
    name: https
